name: example

# Controls when the workflow will run
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: eu-west-1
            role-to-assume: ${{ secrets.ROLE }}
            role-session-name: OIDCSession
        
        - name: Install Python dependencies
          run: python -m pip install pytest bs4 pandas boto3
        
        - name: Train model
          run: python src/test_examples.py
