name: linter-pylint

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [turn_on_ec2]
    types:
      - completed

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  check_collect_data:  
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: Check out repository   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install Python dependencies
      run: python -m pip install pylint

    - name: run pylint
      run: pylint -d C0303 ././src/collect_data.py
