name: linter-pylint

on: 
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  gathering-data:  
    runs-on: ubuntu-22.04
    steps:

    - name: Check out repository   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Python dependencies
      run: python -m pip install pylint

    - name: run pylint
      run: pylint ././src/collect_data.py