name: prefect

on:
  workflow_run:
    workflows: ["turn_on_ec2"]
    types:
      - completed


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  gathering-data:  
    runs-on: self-hosted
    
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::${{ secrets.ROLE }}:role/EC2-S3-Access
        role-session-name: OIDCSession
    
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install Python dependencies
      run: python -m pip install prefect 
      
    - name: start prefect
      run: prefect server start 

        
