name: testing_monitor

on:
  workflow_dispatch: 

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  mlops:  
    runs-on: self-hosted
   
    steps:

    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        role-to-assume: arn:aws:iam::${{ secrets.ROLE }}:role/EC2-S3-Access
        role-session-name: OIDCSession
    
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install Python dependencies
      run: python -m pip install bs4 pandas boto3 evidently

    - name: monitor
      run: |
        output = python src/monitor_datadrift.py
        echo "::set-output name=changelog::$output"
