name: testing

# Controls when the workflow will run
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  BUCKET_NAME : "gas-prices-project"
  AWS_REGION : "eu-west-1"
  
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      
jobs:
  # This workflow contains a single job called "build"
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: eu-west-1
            role-to-assume: arn:aws:iam::${{ secrets.ROLE }}:role/EC2-S3-Access
            role-session-name: OIDCSession
        
        - name: Install Python dependencies
          run: python -m pip install pytest bs4 pandas boto3
        
        - name: Train model
          run: python src/test_examples.py
